In [73]:
import pandas as pd

metadata = pd.read_csv('panel-metadata.csv')

In [74]:
metadata.head()

,tag,hex1,Color,Unnamed: 3,tag2,hex2,Color2
0,PANEL_FALLBACK,NaN,NaN,NaN,NaN,NaN,NaN
1,PANEL_FRONT,e32121,NaN,NaN,PANEL_BACK,285c06,NaN
2,PANEL_LEFT,e8227a,NaN,NaN,PANEL_RIGHT,f84e9a,NaN
3,PANEL_RIGHT_FRONT,35766,NaN,NaN,PANEL_LEFT_FRONT,1b6e7d,NaN
4,PANEL_RIGHT_BACK,037aac,NaN,NaN,PANEL_LEFT_BACK,09658c,NaN

In [75]:
_metadata = metadata.drop(columns=['Color', 'Unnamed: 3', 'Color2'], inplace=False)
_metadata = _metadata.dropna('index', how="all")
_metadata

/tmp/ipykernel_668400/145469886.py:2: FutureWarning: In a future version of pandas all arguments of DataFrame.dropna will be keyword-only.
  _metadata = _metadata.dropna('index', how="all")

                   tag    hex1                        tag2    hex2
0       PANEL_FALLBACK     NaN                         NaN     NaN
1          PANEL_FRONT  e32121                  PANEL_BACK  285c06
2           PANEL_LEFT  e8227a                 PANEL_RIGHT  f84e9a
3    PANEL_RIGHT_FRONT   35766            PANEL_LEFT_FRONT  1b6e7d
4     PANEL_RIGHT_BACK  037aac             PANEL_LEFT_BACK  09658c
..                 ...     ...                         ...     ...
381                NaN     NaN                     TRIM_LR     NaN
382                NaN     NaN                    TRIM_ZSL     NaN
383                NaN     NaN                  TRIM_SSBCL     NaN
384                NaN     NaN  TRIM_B_PLACKET_OVER_WOODEN     NaN
385                NaN     NaN              TRIM_ZST_METAL  343b3c

[319 rows x 4 columns]

In [72]:
tagcol1= _metadata.iloc[:, 0]
tagcol2 = _metadata.iloc[:, 2]

tags = tagcol1.append(tagcol1)

hexcol1= _metadata.iloc[:, 1]
hexcol2 = _metadata.iloc[:, 3]

hexcode = hexcol1.append(hexcol2)

tags.index = range(len(tags))
hexcode.index = range(len(hexcode))

# hexcode.index = range(len(tags)) + 

# hexcode.index = range(len(tags), len(tags)+len(hexcode))

# print(range(len(tags)), range(len(tags), len(tags)+len(hexcode)))

# df = None
# # hexcode = hexcol1 

# # tagcol1.index

df = pd.DataFrame(
    {'tag': tags,'hexcode': hexcode}
    # index = range(len(tags))
)

df

/tmp/ipykernel_668400/1775988469.py:4: FutureWarning: The series.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  tags = tagcol1.append(tagcol1)
/tmp/ipykernel_668400/1775988469.py:9: FutureWarning: The series.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  hexcode = hexcol1.append(hexcol2)

                   tag hexcode
0       PANEL_FALLBACK     NaN
1          PANEL_FRONT  e32121
2           PANEL_LEFT  e8227a
3    PANEL_RIGHT_FRONT   35766
4     PANEL_RIGHT_BACK  037aac
..                 ...     ...
633                NaN     NaN
634                NaN     NaN
635                NaN     NaN
636                NaN     NaN
637                NaN  343b3c

[638 rows x 2 columns]

In [68]:
len(df.index)
_df = df.copy()

_df.columns = ['tag', 'rgb']
# _df
# rgb = []
# # colormaps = {}
for i in df.index:
    hex = df.iloc[i, 1]
    # print(hex)
    
    hex = str(hex)
    if len(hex) == 5:
        hex  = "0" + hex
    # print(len(str(hex)))
    assert len(hex ) == 6 or hex in ["NaN", "nan"], hex

    if hex not in ["NaN", "nan"]:
        rgb = tuple(int(str(hex)[j:j+2], 16) for j in (0, 2, 4))
    else:
        rgb = (0,0,0)

    _df.iloc[i, 1] = rgb

_df

AssertionError: HEX code

In [40]:
_df

                                tag             rgb
0                    PANEL_FALLBACK       (0, 0, 0)
1                       PANEL_FRONT   (227, 33, 33)
2                        PANEL_LEFT  (232, 34, 122)
3                 PANEL_RIGHT_FRONT    (3, 87, 102)
4                  PANEL_RIGHT_BACK   (3, 122, 172)
..                              ...             ...
265        PANEL_CENTER_BACK_BOTTOM       (0, 0, 0)
266   PANEL_CENTER_RIGHT_FRONT_OVER  (123, 73, 120)
267  PANEL_CENTER_RIGHT_FRONT_UNDER    (61, 58, 95)
268         PANEL_CENTER_FRONT_OVER   (61, 84, 132)
269          PANEL_CENTER_BACK_OVER    (36, 57, 99)

[270 rows x 2 columns]

In [51]:
import json

colormaps = {}

# colormaps = dict(zip(listKeys, [None]*len(listKeys)))

for i in _df.index:
    colormaps[_df.iloc[i, 0]] = _df.iloc[i, 1]


# json.dump(colormaps)

# type(colormaps)

with open("colormaps.json", "w") as fp:
    json.dump( colormaps, fp=fp )